- name: purge old docker versions
  ignore_errors: yes
  apt: name={{ item }} purge=yes 
  with_items:
    - lxc-docker*
    - docker.io*

- name: prerequisites (https, ca certificates)
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - ca-certificates
    - apt-transport-https

- name: add Docker key
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: add Docker repo
  apt_repository:
    filename: docker
    repo: deb https://apt.dockerproject.org/repo debian-jessie main
    state: present

- name: update and upgrade
  apt:
    update_cache: yes
    upgrade: full

- name: Docker Install
  apt:
    name: docker-engine
    state: present

- name: docker start
  service:
    name: docker
    state: started
